'From Cuis 5.0 [latest update: #4024] on 16 February 2020 at 4:27:15 pm'!
'Description un logo experimental'!
!provides: 'AtaLogo' 1 0!
SystemOrganization addCategory: #AtaLogo!


!classDefinition: #Tortuga category: #AtaLogo!
Object subclass: #Tortuga
	instanceVariableNames: 'dir estilo lapiz'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'AtaLogo'!
!classDefinition: 'Tortuga class' category: #AtaLogo!
Tortuga class
	instanceVariableNames: ''!


!Tortuga commentStamp: '<historical>' prior: 0!
Soy una tortuga de Logo, me muevo por un plano dejando un rastro si quiero!
